on:
  push:
  workflow_call:
    inputs:
      gcp_project_id:
        required: true
        type: string
      gcp_wi_provider:
        required: true
        type: string
      gcp_serviceaccount:
        required: true
        type: string
      tf_workdir:
        required: false
        type: string
      environment:
        required: true
        type: string
env:
  PROJECT_ID: ${{ inputs.gcp_project_id }}
  TF_WORKDIR: ${{ inputs.tf_workdir }}
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
  checkout-auth-terraform:
    name: Setup auth and Cloud SDK, run Terraform
    runs-on: ubuntu-latest

    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Print environment
      run: |-
        printenv|sort
    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: ${{ inputs.gcp_wi_provider }}
        service_account: ${{ inputs.gcp_serviceaccount }}
        create_credentials_file: true
    - id: output
      name: output token
      run: echo "::set-output name=gcp-token::${{ steps.auth.outputs.access_token }}"
    - id: show gcp token
      run: |
        echo GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
        cat ${GOOGLE_APPLICATION_CREDENTIALS}
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - id: init
      uses: hashicorp/setup-terraform@v2

    - name: Terraform init
      run: |
        [ "${TF_WORKDIR}" != "" ] && cd ${TF_WORKDIR}
        terraform init -backend-config="bucket=${PROJECT_ID}-tfstate" -backend-config="prefix=${GITHUB_REPOSITORY}/${ENVIRONMENT}"
    - id: plan
      name: Terraform plan
      run: |
        [ "${TF_WORKDIR}" != "" ] && cd ${TF_WORKDIR}
        terraform plan -no-color

    - id: apply
      name: Terraform apply
      run: |
        [ "${TF_WORKDIR}" != "" ] && cd ${TF_WORKDIR}
        terraform apply -auto-approve
